### ISSUE TITLE
How to require/import it from npm

### ISSUE THREAD

**Issue by cjroebuck** [pyrsmk/W#11]
Is it possible to require or import the library via npm:

both 
`import W from 'pyrsmk-w'`
and
`require('pyrsmk-w')` 

don't work

**Comment by pyrsmk** [comment]
What is your environment? Node? The browser? Browserify?

**Comment by cjroebuck** [comment]
Browserify/webpack

**Comment by pyrsmk** [comment]
Ok, I'll take a look to `gulp-umd`. W should be callable by browserify, so I don't know why it's not working ;)

**Comment by cjroebuck** [comment]
Yeh, I think W.min.js should be index.js, then it might work?

**Comment by pyrsmk** [comment]
Nope, normally the source file is handled by the `main` directive in `package.json`. How do you integrate W in browerify? How does look your grunt/gulp file?

**Comment by cjroebuck** [comment]
Ahh, that is why, I didn't notice this was specified in package.json. If unspecified it will just pickup index.js in the root dir. 

in package.json `  "main": "src/W.js",` should actually point to `W.min.js`

src/W.js doesn't have the necessary umd/commonjs wrapper so never gets exported.

**Comment by pyrsmk** [comment]
Yep, that was my first clue with [qwest](https://github.com/pyrsmk/qwest). But someone points me out that a main file for package.json shouldn't be modified (especially minified). For the time, all my `package.json` files points to the source file and not the compiled one, because I don't really know what to do. Anyway, you can import W by hand in browserify with `W.min.js`, isn't it?

**Comment by cjroebuck** [comment]
Yep, maybe you could export a W.js and a W.min.js from your gulp build and point to W.js as the main source file to be imported by default. Then keep src/W.js as the plain source file with no ugly umd wrapper etc. I'm not using W anymore but would be good to get it working how most people expect when importing npm packages using browserify or webpack. (im actually using webpack).

**Comment by pyrsmk** [comment]
You're right, I should think about it.

Just to know, what are you using instead of W?

**Comment by cjroebuck** [comment]
Oh, I only really needed W for one tiny call, and realised I could just use a plain javascript dom method (window.innerWidth) or something rather than figure out why W wasn't importing properly! 

I would come back to W in the future though when I need something like this again - assuming the import situation is improved ;)

**Comment by pyrsmk** [comment]
Ok ;)

Just to let you know, W as several routines to correctly detect the viewport dimensions. You can't only rely on `window.innerWidth` if you want responsive.
