### ISSUE TITLE
orientation change for iOS

### ISSUE THREAD

**Issue by headwinds** [pyrsmk/W#7]
I really like the ease of W and need to get the iOS orientation change event working so let's look at this issue as a group and drop that caveat ;-D

[stackoverflow has something to say about it](http://stackoverflow.com/questions/5284878/how-do-i-correctly-detect-orientation-change-using-javascript-and-phonegap-in-io)

**Comment by headwinds** [comment]
If we know the orientation will always be portrait on iOS devices - do we at least get a resize event when it changes? If so, I'm thinking we can simply flip height and width

      var winHeight = W.getViewportHeight();
      var winWidth = W.getViewportWidth();

      if ( winHeight <  winWidth ) {
        // flip it for landscape
        winHeight = W.getViewportWidth();
        winHeight = W.getViewportHeight();
      }

I'll test this...

**Comment by pyrsmk** [comment]
Orientation change is not supported for iOS5/6, but is supported for iOS>=7. So, is this really a need? ^^

Logically, W will trigger all callbacks registered with `addListener()` if the orientations changes. It's just unable to know in what orientation we are because iOS5 returns weird values.

**Comment by pyrsmk** [comment]
To a explain a bit more... With iOS we need to have the orientation to know what values to retrieve for the viewport's width/height. So, we can't rely on `getViewportWidth/Height()` to know what the orientation is.

**Comment by headwinds** [comment]
I'm idiot - yes you're absolutely right - no need! Sorry for some reason my brain equated iOS 6 as iPhone 6 - obviously we're all on iOS 8+ now - thanks! Doh

**Comment by pyrsmk** [comment]
Ahah, so there's no problem! Yay!
