### ISSUE TITLE
Remove listener 

### ISSUE THREAD

**Issue by davidbani** [pyrsmk/W#8]
Hi, is there a way to remove the listener? Thanks for developing this tool.

**Comment by pyrsmk** [comment]
Nope, but it should be. Maybe adding an optional label to a listener would fix simply fix this without breaking compatibility : 

```js
W.addListener(function(){}, 'mylistener');
W.removeListener('mylistener');
```

**Comment by davidbani** [comment]
@pyrsmk ah yeh. Makes sense, thanks.

**Comment by pyrsmk** [comment]
Hey! It's not pushed yet :p 
I'm making the changes, I'll update the library in a couple of hours ;)

**Comment by davidbani** [comment]
@pyrsmk oh, I don't know why I closed this, yeh no rush :P cheers.

**Comment by pyrsmk** [comment]
Pushed!
